export const iconCategories = [
  { name: "Accessibility", icon: "fa-brands fa-accessible-icon" },
  { name: "Alert", icon: "fa-solid fa-bell-on" },
  { name: "Alphabet", icon: "fa-solid fa-circle-a" },
  { name: "Animals", icon: "fa-solid fa-cat" },
  { name: "Arrows", icon: "fa-solid fa-square-up-right" },
  { name: "Astronomy", icon: "fa-solid fa-planet-ringed" },
  { name: "Automotive", icon: "fa-solid fa-car-side" },
  { name: "Buildings", icon: "fa-solid fa-landmark" },
  { name: "Business", icon: "fa-solid fa-briefcase" },
  { name: "Camping", icon: "fa-solid fa-campfire" },
  { name: "Charity", icon: "fa-solid fa-hands-holding-heart" },
  { name: "Charts + Diagrams", icon: "fa-solid fa-chart-simple" },
  { name: "Childhood", icon: "fa-solid fa-balloons" },
  { name: "Clothing + Fashion", icon: "fa-solid fa-shirt" },
  { name: "Coding", icon: "fa-solid fa-code" },
  { name: "Communication", icon: "fa-solid fa-message-dots" },
  { name: "Connectivity", icon: "fa-solid fa-signal" },
  { name: "Construction", icon: "fa-solid fa-person-digging" },
  { name: "Design", icon: "fa-solid fa-palette" },
  { name: "Devices + Hardware", icon: "fa-solid fa-computer" },
  { name: "Disaster + Crisis", icon: "fa-solid fa-burst" },
  { name: "Editing", icon: "fa-solid fa-pen-line" },
  { name: "Education", icon: "fa-solid fa-graduation-cap" },
  { name: "Emoji", icon: "fa-solid fa-face-laugh" },
  { name: "Energy", icon: "fa-solid fa-bolt" },
  { name: "Files", icon: "fa-solid fa-files" },
  { name: "Film + Video", icon: "fa-solid fa-film" },
  { name: "Food + Beverage", icon: "fa-solid fa-burger-soda" },
  { name: "Fruits + Vegetables", icon: "fa-solid fa-strawberry" },
  { name: "Gaming", icon: "fa-solid fa-joystick" },
  { name: "Genders", icon: "fa-solid fa-venus-mars" },
  { name: "Halloween", icon: "fa-solid fa-jack-o-lantern" },
  { name: "Hands", icon: "fa-solid fa-hand" },
  { name: "Holidays", icon: "fa-solid fa-party-horn" },
  { name: "Household", icon: "fa-solid fa-bed-front" },
  { name: "Humanitarian", icon: "fa-solid fa-parachute-box" },
  { name: "Logistics", icon: "fa-solid fa-truck-fast" },
  { name: "Maps", icon: "fa-solid fa-map" },
  { name: "Maritime", icon: "fa-solid fa-anchor" },
  { name: "Marketing", icon: "fa-solid fa-bullseye-arrow" },
  { name: "Mathematics", icon: "fa-solid fa-abacus" },
  { name: "Media Playback", icon: "fa-solid fa-play-pause" },
  { name: "Medical + Health", icon: "fa-solid fa-stethoscope" },
  { name: "Money", icon: "fa-solid fa-money-bill-simple-wave" },
  { name: "Moving", icon: "fa-solid fa-box-taped" },
  { name: "Music + Audio", icon: "fa-solid fa-music" },
  { name: "Nature", icon: "fa-solid fa-trees" },
  { name: "Numbers", icon: "fa-solid fa-circle-2" },
  { name: "Photos + Images", icon: "fa-solid fa-camera-retro" },
  { name: "Political", icon: "fa-solid fa-check-double" },
  { name: "Punctuation + Symbols", icon: "fa-solid fa-quote-left" },
  { name: "Religion", icon: "fa-solid fa-person-praying" },
  { name: "Science", icon: "fa-solid fa-atom-simple" },
  { name: "Science Fiction", icon: "fa-solid fa-raygun" },
  { name: "Security", icon: "fa-solid fa-shield" },
  { name: "Shapes", icon: "fa-solid fa-shapes" },
  { name: "Shopping", icon: "fa-solid fa-bag-shopping" },
  { name: "Social", icon: "fa-solid fa-hashtag" },
  { name: "Spinners", icon: "fa-solid fa-rotate" },
  { name: "Sports + Fitness", icon: "fa-solid fa-heart-pulse" },
  { name: "Text Formatting", icon: "fa-solid fa-text-size" },
  { name: "Time", icon: "fa-solid fa-calendar-days" },
  { name: "Toggle", icon: "fa-solid fa-toggle-on" },
  { name: "Transportation", icon: "fa-solid fa-taxi-bus" },
  { name: "Travel + Hotel", icon: "fa-solid fa-spa" },
  { name: "Users + People", icon: "fa-solid fa-people-simple" },
  { name: "Weather", icon: "fa-solid fa-cloud-sun" },
  { name: "Writing", icon: "fa-solid fa-typewriter" },
  { name: "Uncategorised", icon: "fa-solid fa-union" },
];
