export const tempIcons = [
  {
    icon: "fa-solid fa-dice-five",
    category: ["Gaming", "Travel + Hotel"],
    family: "Classic",
    license: "Free",
    Style: "Solid",
  },
  {
    icon: "fa-solid fa-dice-four",
    category: ["Gaming"],
    family: "Classic",
    license: "Free",
    Style: "Solid",
  },
  {
    icon: "fa-solid fa-dice-one",
    category: ["Gaming"],
    family: "Classic",
    license: "Free",
    Style: "Solid",
  },
  {
    icon: "fa-solid fa-dice-six",
    category: ["Gaming"],
    family: "Classic",
    license: "Free",
    Style: "Solid",
  },
  {
    icon: "fa-solid fa-dice-three",
    category: ["Gaming"],
    family: "Classic",
    license: "Free",
    Style: "Solid",
  },
  {
    icon: "fa-solid fa-dice-two",
    category: ["Gaming"],
    family: "Classic",
    license: "Free",
    Style: "Solid",
  },
  {
    icon: "fa-solid fa-diploma",
    category: ["Uncategorised"],
    family: "Sharp",
    license: "Pro",
    Style: "Solid",
  },
  {
    icon: "fa-solid fa-disc-drive",
    category: ["Uncategorised"],
    family: "Sharp",
    license: "Pro",
    Style: "Solid",
  },
  {
    icon: "fa-solid fa-disease",
    category: ["Medical + Health", "Science"],
    family: "Classic",
    license: "Free",
    Style: "Solid",
  },
  {
    icon: "fa-solid fa-display",
    category: ["Devices + Hardware", "Humanitarian"],
    family: "Classic",
    license: "Free",
    Style: "Solid",
  },
  {
    icon: "fa-solid fa-display-arrow-down",
    category: ["Arrows"],
    family: "Classic",
    license: "Free",
    Style: "Solid",
  },
  {
    icon: "fa-solid fa-display-code",
    category: ["Devices + Hardware"],
    family: "Classic",
    license: "Free",
    Style: "Solid",
  },
  {
    icon: "fa-solid fa-display-medical",
    category: ["Devices + Hardware"],
    family: "Classic",
    license: "Free",
    Style: "Solid",
  },
  {
    icon: "fa-solid fa-display-slash",
    category: ["Devices + Hardware"],
    family: "Classic",
    license: "Free",
    Style: "Solid",
  },
  {
    icon: "fa-solid fa-distribute-spacing-horizontal",
    category: ["Uncategorised"],
    family: "Sharp",
    license: "Pro",
    Style: "Solid",
  },
  {
    icon: "fa-solid fa-distribute-spacing-vertical",
    category: ["Uncategorised"],
    family: "Sharp",
    license: "Pro",
    Style: "Solid",
  },
  {
    icon: "fa-solid fa-ditto",
    category: ["Uncategorised"],
    family: "Sharp",
    license: "Pro",
    Style: "Solid",
  },
  {
    icon: "fa-solid fa-divide",
    category: ["Mathematics"],
    family: "Classic",
    license: "Free",
    Style: "Solid",
  },
  {
    icon: "fa-solid fa-dna",
    category: ["Medical + Health", "Science"],
    family: "Classic",
    license: "Free",
    Style: "Solid",
  },
  {
    icon: "fa-solid fa-do-not-enter",
    category: ["Uncategorised"],
    family: "Sharp",
    license: "Pro",
    Style: "Solid",
  },
];
